# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.7.7'

gem 'sinatra-activerecord'
gem 'sinatra-embedded-shopify-app', path: '../'
gem 'sinatra-flash'

group :production do
  gem 'pg'
end

group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
end

group :development do
  gem 'rake', '>= 12.3.3'
end

group :test do
  gem 'fakeweb'
  gem 'minitest'
  gem 'mocha', require: false
  gem 'rack-test'
end
